language: node_js
node_js:
- '0.11'
env:
  global:
  - AWS_REGION="us-east-1"
  - AWS_S3_BUCKET="hakobera-transfer-test"
  - AWS_DYNAMODB_TABLE="transfer_test"
  - secure: Qa6QMdcxDLIz1eYV4nXiGQuYkDu4IsgleAezx/s+Ym7FdBJJEVmoljsop/adF1hMKeE2Rz766OrNxj/nMbU168DXhZ3bwWctGjU6xRUpJzlW+UFsdzePdnNOys5ejwZ+bZq9AQd+D9HaQEb+ccXurdcFCBT1njSoMGRDRYW+1AE=
  - secure: abz4vP8uAe98ahdmYBJr6mMvI6uUxekc+ZHY7gxzBkG4vXzOeXBY2XEEN4qwdeLo7IiyZbZySQoyi2dqOW2/vRxb3S2PtYfDhkdvduBIjjOdbZfaKnuMs9AqbgCWut0DdG+57O2a3Oerv1c4EJ1XYIILf1iGxvsUd3ymtTMGQDI=
